# Generated by Django 2.2 on 2021-11-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar_name', models.CharField(max_length=50)),
                ('imageURL', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('creator_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('creator_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('imageURL', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('avatar', models.ManyToManyField(related_name='items', to='app.Avatar')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.Creator')),
            ],
        ),
        migrations.AddField(
            model_name='avatar',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='app.Creator'),
        ),
    ]
