# Generated by Django 2.2 on 2021-12-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211206_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imageURL',
            field=models.CharField(max_length=99),
        ),
    ]
