# Generated by Django 2.2 on 2021-12-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211206_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar_name',
            field=models.CharField(max_length=200),
        ),
    ]
