# Generated by Django 2.2 on 2021-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211206_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='creator_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='imageURL',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
