# Generated by Django 2.2 on 2022-03-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211206_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='item_num_0',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='item_num_1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='item_num_2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='item_num_3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='item_num_4',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='item_num_5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='item_num_6',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='item',
            name='avatar',
            field=models.ManyToManyField(blank=True, related_name='items', to='app.Avatar'),
        ),
    ]
