# Generated by Django 2.2 on 2022-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220310_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='item_hot',
            field=models.IntegerField(default=0),
        ),
    ]
