# Generated by Django 2.2 on 2022-03-22 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app', '0008_avatar_item_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('VRCID', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('isSupporter', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='avatar',
            name='item_num_0',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='item_num_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='item_num_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='item_num_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='item_num_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='item_num_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='item_num_6',
            field=models.IntegerField(default=0),
        ),
    ]
