# Generated by Django 2.2 on 2022-03-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220323_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='screen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('fav_avatar', models.ManyToManyField(to='app.Avatar')),
                ('fav_item', models.ManyToManyField(to='app.Item')),
            ],
        ),
    ]
