# Generated by Django 2.2 on 2022-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220324_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
