# Generated by Django 3.2.9 on 2022-03-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
    ]
