# Generated by Django 3.2.9 on 2022-03-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_folder_isopen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ItemQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='folder',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='app.customer'),
        ),
    ]
