# Generated by Django 3.2.9 on 2022-03-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220329_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatarqueue',
            old_name='name',
            new_name='avatar_name',
        ),
        migrations.RenameField(
            model_name='itemqueue',
            old_name='name',
            new_name='item_name',
        ),
    ]
