# Generated by Django 2.2 on 2022-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220329_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='isNSFW',
            field=models.BooleanField(default=False),
        ),
    ]
