# Generated by Django 2.2 on 2022-03-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_folder_isnsfw'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='highlight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Creator'),
        ),
    ]
