# Generated by Django 2.2 on 2022-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customer_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='VRCID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
