# Generated by Django 2.2 on 2022-05-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220416_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Avatar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item')),
            ],
        ),
    ]
