# Generated by Django 2.2 on 2022-12-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_relationqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='want_avatar',
            field=models.ManyToManyField(related_name='want_avatar', to='app.Avatar'),
        ),
        migrations.AddField(
            model_name='folder',
            name='want_item',
            field=models.ManyToManyField(related_name='want_item', to='app.Item'),
        ),
    ]
